version: '3.8'

services:
  traefik:
    image: traefik:v3.0 # Or desired version
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --providers.file.directory=/etc/traefik/certs
      - --providers.file.watch=true
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/certs:/etc/traefik/certs:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - web
  web:
    image: ghcr.io/abdul-basit780/shop-ease:latest
    container_name: web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-app.rule=Host(`shop-ease.dev`)"
      - "traefik.http.routers.my-app.entrypoints=websecure"
      - "traefik.http.routers.my-app.tls=true"
    restart: always
    env_file:
      - ./web.env
    networks:
      - web
networks:
  web:
    external: true # Or create if not external
