name: Build and Test

on:
  push:

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build application
      - name: Build
        run: npm run build

      # Run tests
      - name: Test
        run: npm run test

      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      # Collect coverage
      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Coverage
        with:
          prnumber: ${{ steps.findPr.outputs.number }}

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build . --tag ghcr.io/abdul-basit780/shop-ease

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ghcr.io/abdul-basit780/shop-ease

      # SSH to remote host and execute commands
      - name: SSH to remote host and execute commands
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: shop-ease.dev  # IP or hostname of the remote host
          username: root  # SSH username
          key: ${{ secrets.SSH_KEY }}  # SSH private key (use GitHub Secrets)
          port: 22  # Default SSH port, adjust if needed
          script: |
            echo "Running commands on remote host"